// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPSBallRuleIOS
{
        public const string achievement_proficient = "CgkIw8vtoN8WEAIQAg"; // <GPGSID>
        public const string leaderboard_universal = "CgkIw8vtoN8WEAIQBg"; // <GPGSID>
        public const string leaderboard_supporters = "CgkIw8vtoN8WEAIQCQ"; // <GPGSID>
        public const string achievement_expert = "CgkIw8vtoN8WEAIQBA"; // <GPGSID>
        public const string achievement_newbie = "CgkIw8vtoN8WEAIQAA"; // <GPGSID>
        public const string leaderboard_obstacles = "CgkIw8vtoN8WEAIQCA"; // <GPGSID>
        public const string leaderboard_challenge = "CgkIw8vtoN8WEAIQBw"; // <GPGSID>
        public const string achievement_advance = "CgkIw8vtoN8WEAIQAw"; // <GPGSID>
        public const string achievement_intermediate = "CgkIw8vtoN8WEAIQAQ"; // <GPGSID>

}

